### ISSUE TITLE
It's not working and what kind of prompts would work can be mentioned in the readme file

### ISSUE THREAD

**Issue by akash1520** [matthewdowney/rendergpt#3]
I literally copy pasted the prompt you have mentioned in your extension overview and it didn't work. Btw just pointing out to let you know, also I want to work on this, can I?
<img width="960" alt="image" src="https://github.com/matthewdowney/rendergpt/assets/82609252/7c6240ab-51a9-49c5-bcc8-768908e94353">

**Comment by matthewdowney** [comment]
likely due to #2, which is fixed in the latest release here, but still pending review in the chrome store. 

in the meantime it should work if you install the extension from manually.

**Comment by akash1520** [comment]
Oh my bad. Btw as I mentioned earlier I would love to work on this, is there anything I can help you with?

**Comment by matthewdowney** [comment]
sure if you have any features you'd like to add, hack away. if looking for suggestions, maybe it'd be cool to get the openai browsing plugin working with plotting in rendergpt? but other than just keeping it working, there's nothing i'm planning to add to this right now.
