### ISSUE TITLE
Manifest file not being detected

### ISSUE THREAD

**Issue by alowave223** [matthewdowney/rendergpt#4]
I extracted the folder form zip file and then tried to add it to extensions, but constantly getting this error:
![image](https://github.com/matthewdowney/rendergpt/assets/49539029/c9a31264-6d9f-4ce5-a5dd-d9f61c8eee5c)

**Comment by matthewdowney** [comment]
Ah that's right, the latest release only included the source code, not the compiled artifact, which I've just uploaded to the release page [here](https://github.com/matthewdowney/rendergpt/releases/tag/v0.3.0) (the rendergpt.20230603092056.zip file).

The most recent version is on the Chrome Store [here](https://chrome.google.com/webstore/detail/rendergpt/faedgcadnkineopgicfikgggjjapeeon/related), too.
